### PR TITLE
Simplified arguments copying

### PR DESCRIPTION
**Pull request by istvan-antal**
Instead of using a for loop, we could just use the native Array.slice to copy the arguments object into an array.

### CODE REVIEW

**Comment by tgriesser** [comment]
Hey @istvan-antal, thanks for the pull request. So actually this was a conscious decision, as according [to this optimization guide](https://github.com/petkaantonov/bluebird/wiki/Optimization-killers#3-managing-arguments) (see 3.2) `slice` leaks arguments and prevents the function from being optimized.

**Comment by istvan-antal** [comment]
I don't think the micro optimization V8 gives is worth it in this case. There are a lot of things are suboptimal in V8 like Array.forEach, chasing V8 is not worth it, unless you are writing something really performance critical.

**Comment by tgriesser** [comment]
I'd tend to agree, but in this case it's not a micro-optimization but actually preventing the entire function from being optimized, as is seen by the `%OptimizeFunctionOnNextCall` and `%GetOptimizationStatus` when running node with the `--trace_opt --trace_deopt --allow-natives-syntax` flags... if this is something to be used as the foundation for Errors in a lot of places, I'd rather add 2 or 3 extra lines than knowingly write code that can't be optimized.

Also, switching from when.js to bluebird for promises in my other libraries (knex & bookshelf), where @petkaantonov employs the techniques he mentions in the optimization guide cuts the test suite from 3s to 1s runtime.

**Comment by istvan-antal** [comment]
I understand, thank you for the clarification.

**Comment by petkaantonov** [comment]
Similar pull request in node core: https://github.com/joyent/node/pull/6278

**Comment by tgriesser** [comment]
@petkaantonov - curious, would 

``` js
return function() {
  var args = safeArgs.apply(null, arguments);
  // ...
}

function safeArgs() {
  var args = new Array(arguments.length);
  for (var i = 0; i < args.length; ++i) {
    args[i] = arguments[i];
  }
  return args;
}
```

be just as (or close to as) efficient as the inlined approach - since it's using `arguments` safely with `apply`?

**Pull request closed without merging**
